#!/usr/local/bin/perl -w

$pi = 3.141592654;

print "Please enter a circle radius\n";
chomp($radius = <STDIN>);

if ($radius < 0) {
  $circumference = 0;
}
else {
  $circumference = (2 * $pi) * $radius;
}

print "The circumerence of a circle with radius ${radius} is ${circumference}.\n";


